### ISSUE TITLE
Hardcoded bandpass filter 

### ISSUE THREAD

**Issue by edeguzman** [functional-neuroimaging/rsfMRI-preprocessing#2]
@marcopagani-brainconnectivity 
In rsfmri_preprocess_09_bandpass_filter.sh the bounds of the bandpass filter are hard coded in the command. There are two lines at the top of the script (marked with "edit here") which appear to control the bandpass filter limits, but actually do nothing upon closer inspection. This is confusing. Can we please either remove the "edit here" variables, or actually use the variables in the call to 3dBandpass?

**Comment by marcopagani-brainconnectivity** [comment]
Oh yes!! ☺

From: Elizabeth de Guzman ***@***.***>
Sent: Monday, July 11, 2022 9:01 AM
To: functional-neuroimaging/rsfMRI-preprocessing ***@***.***>
Cc: Marco Pagani ***@***.***>; Mention ***@***.***>
Subject: [functional-neuroimaging/rsfMRI-preprocessing] Hardcoded bandpass filter (Issue #2)


@marcopagani-brainconnectivity<https://es.sonicurlprotection-fra.com/click?PV=2&MSGID=202207111301140136368&URLID=3&ESV=10.0.16.7295&IV=1E3849346F890F1673C87CF5707E26C7&TT=1657544476650&ESN=HSmKjK0Ri7qrimNHPvhDpSNbUlAiraePeElKmHWZpXc%3D&KV=1536961729280&B64_ENCODED_URL=aHR0cHM6Ly9naXRodWIuY29tL21hcmNvcGFnYW5pLWJyYWluY29ubmVjdGl2aXR5&HK=8E78BC47EB2434B46A9E8C9903C3D284DF0A6CB0290CF3EDDE28C2BFAC7E496E>
In rsfmri_preprocess_09_bandpass_filter.sh the bounds of the bandpass filter are hard coded in the command. There are two lines at the top of the script (marked with "edit here") which appear to control the bandpass filter limits, but actually do nothing upon closer inspection. This is confusing. Can we please either remove the "edit here" variables, or actually use the variables in the call to 3dBandpass?
